#!/bin/bash

echo "🚀 Deploying Essence Radio to Render..."

echo "📋 Manual Steps Required:"
echo ""
echo "1. Go to https://render.com and sign up"
echo "2. Create a new Web Service:"
echo "   - Connect your GitHub repository"
echo "   - Root Directory: backend"
echo "   - Build Command: npm install && npm run build"
echo "   - Start Command: npm run start:prod"
echo ""
echo "3. Add Environment Variables:"
echo "   - NODE_ENV=production"
echo "   - DB_HOST=(from database service)"
echo "   - DB_USERNAME=(from database service)"
echo "   - DB_PASSWORD=(from database service)"
echo "   - DB_DATABASE=essence_radio"
echo "   - JWT_SECRET=(generate a secure random string)"
echo "   - PORT=3000"
echo ""
echo "4. Create PostgreSQL Database:"
echo "   - Name: essence-mysql"
echo "   - Note: Render uses PostgreSQL, not MySQL"
echo "   - You'll need to update backend to use PostgreSQL"
echo ""
echo "5. Deploy Web Service:"
echo "   - Root Directory: web"
echo "   - Build Command: npm install && npm run build"
echo "   - Publish Directory: dist"
echo "   - Add Environment Variable: VITE_API_URL=https://your-backend.onrender.com"
echo ""
echo "⚠️  Note: Render uses PostgreSQL. Update backend/src/app.module.ts to use 'postgres' instead of 'mysql'"

